### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [RLD-JL/Just-Listen#15]
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I was able to successfully generate the APK using `./gradlew assembleRelease`, but the resulting APKs were not identical. Was that APK really built from a clean tree at the commit the tag points to? If so, did I miss some build options? And if not, which commit was it?

The APK diff shows differences in `classes.dex`, which then result in differences at `baseline.prof` (which cointains a.o. the checksum of `classes.dex`):

```diff
-------------------------------
--- /dev/fd/63  2024-06-25 17:17:30.045808607 +0200
+++ /dev/fd/62  2024-06-25 17:17:30.045808607 +0200
@@ -1,11 +1,11 @@
   META-INF/com/android/build/gradle/app-metadata.properties
   32-bit CRC value (hex):                         37fbe4f4
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         0112ea07
+  32-bit CRC value (hex):                         d0079313
   assets/dexopt/baseline.profm
   32-bit CRC value (hex):                         1588f5de
   classes.dex
-  32-bit CRC value (hex):                         485cc093
+  32-bit CRC value (hex):                         ace09628
   DebugProbesKt.bin
   32-bit CRC value (hex):                         d5ac4dc2
   META-INF/androidx.activity_activity-compose.version
```

Looking at the diff of the Dex file, it seems some ordering differs:

```diff
--- /tmp/tmp.EfoCLn1pUD 2024-07-20 00:04:44.199368243 +0200
+++ /tmp/tmp.3YbKF077hC 2024-07-20 00:04:45.207361549 +0200
@@ -1,9 +1,9 @@
-Processing '/tmp/tmp.sCNuSrjQjU'...
-Opened '/tmp/tmp.sCNuSrjQjU', DEX version '035'
+Processing '/tmp/tmp.I9uc0mXYkR'...
+Opened '/tmp/tmp.I9uc0mXYkR', DEX version '035'
 DEX file header:
 magic               : 'dex\n035\0'
-checksum            : 0e4fba24
-signature           : 66e9...5e37
+checksum            : e16bb9c0
+signature           : d665...5e7f
 file_size           : 4604280
 header_size         : 112
 link_size           : 0
@@ -579761,13 +579761,13 @@
 |: invoke-virtual {v4}, Ljava/lang/Object;.getClass:()Ljava/lang/Class;
 |: const-string v4, "CREATE TABLE AddPlaylist  (\n       playlistName TEXT NOT NULL PRIMARY KEY ,\n       playlistDescription TEXT,\n       songsList TEXT\n)"
 |: invoke-virtual {v0, v2, v4, v2}, LK4/j;.c:(Ljava/lang/Integer;Ljava/lang/String;LD5/c;)V
-|: const-string v4, "CREATE TABLE Library  (\n     id TEXT NOT NULL PRIMARY KEY,\n       title TEXT NOT NULL,\n       user TEXT NOT NULL,\n       songImgList TEXT NOT NULL,\n       playlistName TEXT NOT NULL,\n       recentPlayed INTEGER
+|: const-string v4, "CREATE TABLE SettingsInfo (\n     id INTEGER PRIMARY KEY DEFAULT 1,\n     hasNavigationDonationOn INTEGER NOT NULL,\n     isDarkThemeOn  INTEGER  NOT NULL,\n     palletColor  TEXT  NOT NULL\n)"
 |: invoke-virtual {v0, v2, v4, v2}, LK4/j;.c:(Ljava/lang/Integer;Ljava/lang/String;LD5/c;)V
 |: const-string v4, "CREATE TABLE PlaylistDetail  (\n   id TEXT NOT NULL PRIMARY KEY,\n   title TEXT NOT NULL,\n   playlistName TEXT NOT NULL,\n   songImgList TEXT NOT NULL,\n   user TEXT NOT NULL\n)"
 |: invoke-virtual {v0, v2, v4, v2}, LK4/j;.c:(Ljava/lang/Integer;Ljava/lang/String;LD5/c;)V
 |: const-string v4, "CREATE TABLE SearchScreenInfo  (\n   searchFor TEXT NOT NULL PRIMARY KEY\n)"
 |: invoke-virtual {v0, v2, v4, v2}, LK4/j;.c:(Ljava/lang/Integer;Ljava/lang/String;LD5/c;)V
-|: const-string v4, "CREATE TABLE SettingsInfo (\n     id INTEGER PRIMARY KEY DEFAULT 1,\n     hasNavigationDonationOn INTEGER NOT NULL,\n     isDarkThemeOn  INTEGER  NOT NULL,\n     palletColor  TEXT  NOT NULL\n)"
+|: const-string v4, "CREATE TABLE Library  (\n     id TEXT NOT NULL PRIMARY KEY,\n       title TEXT NOT NULL,\n       user TEXT NOT NULL,\n       songImgList TEXT NOT NULL,\n       playlistName TEXT NOT NULL,\n       recentPlayed INTEGER
 |: invoke-virtual {v0, v2, v4, v2}, LK4/j;.c:(Ljava/lang/Integer;Ljava/lang/String;LD5/c;)V
 |: const-string v4, "INSERT INTO SettingsInfo(hasNavigationDonationOn, isDarkThemeOn, palletColor) VALUES (0, 1, \"Dark\")"
 |: invoke-virtual {v0, v2, v4, v2}, LK4/j;.c:(Ljava/lang/Integer;Ljava/lang/String;LD5/c;)V
```

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by RLD-JL** [comment]
I do not remember on what commit i've built the apk, try for the new one that I have updated today, it is based on what got merged, though it might have issues with jvm target, which i cant bother rn to fix it.

PS: does this app even get downloaded from izzy?

**Comment by IzzySoft** [comment]
Hm, that was definitely not built from the tag at the commit:

```diff
--- /dev/fd/63  2024-08-19 23:51:56.458251061 +0200
+++ /dev/fd/62  2024-08-19 23:51:56.458251061 +0200
@@ -1,13 +1,13 @@
   META-INF/com/android/build/gradle/app-metadata.properties
   32-bit CRC value (hex):                         981abecf
   META-INF/version-control-info.textproto
-  32-bit CRC value (hex):                         beaf51f7
+  32-bit CRC value (hex):                         48daaa6d
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         e712dec0
+  32-bit CRC value (hex):                         7e2e6af8
   assets/dexopt/baseline.profm
   32-bit CRC value (hex):                         6449667f
   classes.dex
-  32-bit CRC value (hex):                         2b068346
+  32-bit CRC value (hex):                         e5b1e884
   DebugProbesKt.bin
   32-bit CRC value (hex):                         2d73be70
   META-INF/NOTICE.md
@@ -183,11 +183,11 @@
   META-INF/kotlinx_coroutines_slf4j.version
   32-bit CRC value (hex):                         6a2f0318
   META-INF/services/c6.x
-  32-bit CRC value (hex):                         5203f1d9
+  32-bit CRC value (hex):                         fa1d0a3c
   META-INF/services/d6.a
-  32-bit CRC value (hex):                         50454f80
+  32-bit CRC value (hex):                         d13059ff
   META-INF/services/e5.g
-  32-bit CRC value (hex):                         5d88d186
+  32-bit CRC value (hex):                         71c46175
   kotlin-tooling-metadata.json
   32-bit CRC value (hex):                         e88190dd
```

`version-control-info.textproto` says otherwise:

```
repositories {
  system: GIT
  local_root_path: "$PROJECT_DIR"
  revision: "97abe48572a4b2670ccc35bbdaab88336b14dc27"
}
```

Trying another build at that commit now. Meanwhile: as the "first basic rule" at above linked [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) says, please always build the APKs from a clean tree at the commit the tag points to. Forgetting that makes up about 80% of all RB failures I've seen so far. Luckily the embedded VcsInfo often gives us a clue here – but if the tree was dirty, and other changes followed before finally committing the tag, there's no chance to get it RB.

Second build is through: nope, no chance. Must be exactly the case I just described: neither here nor there. The APK was built somewhere **between** the commit embedded in the VcsInfo, and the one used for the tag (even before the commit in between of the two). Can you provide an APK built from the tag directly, and attach it to a comment here (just **rename** the file to `*.zip` so you can attach it, do not put it inside another zip if possible). I'd then try again with that.

**Comment by IzzySoft** [comment]
Do you by any chance use SQLDelight? You do, I see. That might be the culprit. You might want to check with https://github.com/LeoColman/Petals/issues/675#issuecomment-2299506527 where the author found that.

**Comment by RLD-JL** [comment]
> Do you by any chance use SQLDelight? You do, I see. That might be the culprit. You might want to check with [LeoColman/Petals#675 (comment)](https://github.com/LeoColman/Petals/issues/675#issuecomment-2299506527) where the author found that.

Updated the sqldelight library, maybe it works now

**Comment by IzzySoft** [comment]
Congrats, that did it! Added some fixes (you build on Windows, we on Linux), so:

```yaml
- ./gradlew assembleRelease
- git clone -b v0.2.8 https://github.com/obfusk/reproducible-apk-tools.git
- OUT=androidApp/build/outputs/apk/release/androidApp-release-unsigned.apk
- reproducible-apk-tools/inplace-fix.py --internal --zipalign fix-newlines "$OUT" 'META-INF/services/*'
```

and it is RB :partying_face: So you've earned your [welcome toot](https://floss.social/@IzzyOnDroid/113285602305322129) as well:

![image](https://github.com/user-attachments/assets/867c10ae-3254-4bb5-9765-2a7f4c979d9f)

Thanks for your help with this! :star_struck:
